"""
cleanup.py
----------
Transcript cleanup using a local LLM via Ollama.
Fixes grammar errors, misheard words, and punctuation.
"""

from src.chunking import split_blocks
from src.errors import OllamaError
from src.logger import get_logger
from src.ollama_client import DEFAULT_TIMEOUT, call_ollama, check_ollama


DEFAULT_CHUNK_CHARS = 6000

_PROMPT = """You are a transcript editor. Clean up this meeting transcript that was generated by automatic speech recognition (ASR).

Rules:
- Fix obvious speech recognition errors (wrong words that sound similar)
- Fix grammar and punctuation
- Do NOT change the meaning or content of what was said
- Do NOT add information that wasn't there
- Do NOT summarize, shorten or merge what was said — keep every sentence
- Keep the exact speaker labels (e.g. SPEAKER_00:, Marco:) unchanged
- A paragraph with no label continues the previous speaker: leave it unlabelled
- Keep the paragraph breaks exactly where they are — do not merge or add any
- If you're unsure about a word, keep the original
- Respond ONLY with the cleaned transcript, no explanations{part_note}

The transcript language is: {language}

TRANSCRIPT:
{transcript}"""


def cleanup_transcript(
    transcript: str,
    model: str,
    host: str,
    language: str,
    num_ctx: int = None,
    chunk_chars: int = DEFAULT_CHUNK_CHARS,
    timeout: int = DEFAULT_TIMEOUT,
) -> str:
    """
    Cleans up the raw transcript by fixing common speech-to-text errors.

    Long transcripts are cleaned in chunks so nothing falls outside the model's
    context window. If Ollama is unavailable the original transcript is returned
    unchanged — a missing cleanup step should never cost the user a transcript.

    Args:
        transcript:  Raw formatted transcript with speaker labels
        model:       Ollama model to use
        host:        Ollama server URL
        language:    Transcript language
        num_ctx:     Context window to request from Ollama
        chunk_chars: Maximum transcript characters sent in one request
        timeout:     Per-request timeout in seconds

    Returns:
        Cleaned transcript
    """
    log = get_logger()
    log.info(f"[2/4] Cleaning transcript with {model}...")

    if not transcript.strip():
        log.warning("Transcript is empty. Skipping cleanup.")
        return transcript

    if not check_ollama(host, model):
        log.warning(f"Ollama not reachable or model '{model}' not found. Skipping cleanup.")
        return transcript

    chunks = split_blocks(transcript, chunk_chars)
    total = len(chunks)
    if total > 1:
        log.info(f"      Transcript is long — cleaning in {total} chunks.")

    cleaned_parts = []
    for index, chunk in enumerate(chunks, 1):
        if total > 1:
            log.info(f"      Cleaning chunk {index}/{total}...")
        part_note = (
            f"\n- This is part {index} of {total} of a longer transcript; clean only what is given"
            if total > 1 else ""
        )
        prompt = _PROMPT.format(part_note=part_note, language=language, transcript=chunk)
        try:
            cleaned_parts.append(call_ollama(host, model, prompt, num_ctx=num_ctx, timeout=timeout))
        except OllamaError as exc:
            log.error(f"Cleanup failed ({exc}). Keeping the raw transcript.")
            return transcript

    log.info("      Cleanup complete.")
    return "\n\n".join(part for part in cleaned_parts if part.strip()) or transcript
