"""
cleanup.py
----------
Transcript cleanup using a local LLM via Ollama.
Fixes grammar errors, misheard words, and punctuation.
"""

import sys
import requests


def check_ollama(host: str, model: str) -> bool:
    """Checks that Ollama is running and the model is available."""
    try:
        response = requests.get(f"{host}/api/tags", timeout=5)
        if response.status_code != 200:
            return False
        models = [m["name"] for m in response.json().get("models", [])]
        # Check both "llama3.1" and "llama3.1:latest"
        return any(model in m for m in models)
    except requests.exceptions.ConnectionError:
        return False


def call_ollama(host: str, model: str, prompt: str) -> str:
    """Calls Ollama and returns the response."""
    try:
        response = requests.post(
            f"{host}/api/generate",
            json={"model": model, "prompt": prompt, "stream": False},
            timeout=300
        )
        if response.status_code != 200:
            print(f"[ERROR] Ollama responded with status {response.status_code}")
            sys.exit(1)
        return response.json().get("response", "").strip()
    except requests.exceptions.ConnectionError:
        print("[ERROR] Cannot connect to Ollama. Make sure it is running.")
        sys.exit(1)
    except requests.exceptions.Timeout:
        print("[ERROR] Ollama timed out. Try a lighter model.")
        sys.exit(1)


def cleanup_transcript(transcript: str, model: str, host: str, language: str) -> str:
    """
    Cleans up the raw transcript by fixing common speech-to-text errors.

    Args:
        transcript: Raw formatted transcript with speaker labels
        model:      Ollama model to use
        host:       Ollama server URL
        language:   Transcript language

    Returns:
        Cleaned transcript
    """
    print(f"\n[2/4] Cleaning transcript with {model}...")

    if not check_ollama(host, model):
        print(f"[WARNING] Ollama not reachable or model '{model}' not found.")
        print("          Skipping cleanup step.")
        return transcript

    prompt = f"""You are a transcript editor. Clean up this meeting transcript that was generated by automatic speech recognition (ASR).

Rules:
- Fix obvious speech recognition errors (wrong words that sound similar)
- Fix grammar and punctuation
- Do NOT change the meaning or content of what was said
- Do NOT add information that wasn't there
- Keep the exact speaker labels (e.g. SPEAKER_00:, Marco:) unchanged
- Keep the same structure: one speaker block per paragraph
- If you're unsure about a word, keep the original
- Respond ONLY with the cleaned transcript, no explanations

The transcript language is: {language}

TRANSCRIPT:
{transcript}"""

    cleaned = call_ollama(host, model, prompt)
    print("      Cleanup complete.")
    return cleaned
