"""
cleanup.py
----------
Transcript cleanup using a local LLM via Ollama.
Fixes grammar errors, misheard words, and punctuation.
"""

from src.logger import get_logger
from src.ollama_client import check_ollama, call_ollama


def cleanup_transcript(transcript: str, model: str, host: str, language: str) -> str:
    """
    Cleans up the raw transcript by fixing common speech-to-text errors.

    Args:
        transcript: Raw formatted transcript with speaker labels
        model:      Ollama model to use
        host:       Ollama server URL
        language:   Transcript language

    Returns:
        Cleaned transcript
    """
    log = get_logger()
    log.info(f"[2/4] Cleaning transcript with {model}...")

    if not check_ollama(host, model):
        log.warning(f"Ollama not reachable or model '{model}' not found. Skipping cleanup.")
        return transcript

    prompt = f"""You are a transcript editor. Clean up this meeting transcript that was generated by automatic speech recognition (ASR).

Rules:
- Fix obvious speech recognition errors (wrong words that sound similar)
- Fix grammar and punctuation
- Do NOT change the meaning or content of what was said
- Do NOT add information that wasn't there
- Keep the exact speaker labels (e.g. SPEAKER_00:, Marco:) unchanged
- Keep the same structure: one speaker block per paragraph
- If you're unsure about a word, keep the original
- Respond ONLY with the cleaned transcript, no explanations

The transcript language is: {language}

TRANSCRIPT:
{transcript}"""

    cleaned = call_ollama(host, model, prompt)
    log.info("      Cleanup complete.")
    return cleaned
